import { Playfair_Display, Poppins, Mulish } from 'next/font/google';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],  
});

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
   title: "Paulo Moraes Advocacia e Consultoria Jurídica | Advogado em Recife",
  description: "Paulo Moraes Especialista em Advocacia e Consultoria Jurídica, direito do trabalho & previdenciário, Direito civil e família, consultoria jurídica personalizada. Atendimento profissional e confiança para proteger seus direitos.",
   manifest: '/site.webmanifest',
  icons: {
    icon: [
      { url: '/favicon-32x32.png', sizes: '32x32' },
      { url: '/favicon-16x16.png', sizes: '16x16' },
    ],
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  keywords: [
    "advogado Recife",
    "advocacia empresarial",
    "consultoria jurídica Recife",
    "recuperação judicial",
    "falência",
    "advogado especializado",
    "escritório de advocacia Recife",
    "direito empresarial",
    "consultoria jurídica",
    "advogado para empresas",
    "direito civil",
    "paulo moraes advocacia",
    "paulo moraes advogado",
    "paulo moraes",
    "advogado paulo moraes",
    "Paulo Moraes Advocacia e Consultoria Jurídica",
    "direito do trabalho",
    "direito previdenciário",
    "direito civil e família",
    "direito das sucessões",
    "direito médico",
    "direito do consumidor",
    "direito do consumidor Recife",
    "direito do trabalho Recife",
    "direito previdenciário Recife",
    "direito civil e família Recife",
    "direito das sucessões Recife",
    "direito médico Recife",
    "direito do consumidor advogado",
    "direito do trabalho advogado",
    "direito previdenciário advogado",
    "direito civil e família advogado",
    "direito das sucessões advogado",
    "direito médico advogado",
    "direito do consumidor advogado Recife",
    "direito do trabalho advogado Recife",
    "direito previdenciário advogado Recife",
    "direito civil e família advogado Recife",
    "direito das sucessões advogado Recife",
    "direito médico advogado Recife", 
    "direito do consumidor advogado em Recife",
    "direito do trabalho advogado em Recife",
    "direito previdenciário advogado em Recife",
    "direito civil e família advogado em Recife",
    "direito das sucessões advogado em Recife",
    "direito médico advogado em Recife",
    "direito do consumidor advogado em Pernambuco",
    "direito do trabalho advogado em Pernambuco",
    "direito previdenciário advogado em Pernambuco",
    "direito civil e família advogado em Pernambuco",
    "direito das sucessões advogado em Pernambuco",
    "direito médico advogado em Pernambuco",
    "direito do consumidor advogado em Olinda",
    "direito do trabalho advogado em Olinda",
    "direito previdenciário advogado em Olinda",
    "direito civil e família advogado em Olinda",
    "direito das sucessões advogado em Olinda",
    "direito médico advogado em Olinda",
    "direito do consumidor advogado em Jaboatão dos Guararapes",
    "direito do trabalho advogado em Jaboatão dos Guararapes",
    "direito previdenciário advogado em Jaboatão dos Guararapes",
    "direito civil e família advogado em Jaboatão dos Guararapes",
    "direito das sucessões advogado em Jaboatão dos Guararapes",
    "direito médico advogado em Jaboatão dos Guararapes",
    "direito do consumidor advogado em Paulista",
    "direito do trabalho advogado em Paulista",
    "direito previdenciário advogado em Paulista",
    "direito civil e família advogado em Paulista",
    "direito das sucessões advogado em Paulista",
    "direito médico advogado em Paulista",
    "direito do consumidor advogado em Caruaru",
    "direito do trabalho advogado em Caruaru",
    "direito previdenciário advogado em Caruaru",
    "direito civil e família advogado em Caruaru",
    "direito das sucessões advogado em Caruaru",  
    "direito médico advogado em Caruaru",
    "direito do consumidor advogado em Petrolina",
    "direito do trabalho advogado em Petrolina",
    "direito previdenciário advogado em Petrolina",
    "direito civil e família advogado em Petrolina",
    "direito das sucessões advogado em Petrolina",
    "direito médico advogado em Petrolina",
    "direito do consumidor advogado em Garanhuns",
    "direito do trabalho advogado em Garanhuns",
    "direito previdenciário advogado em Garanhuns",
    "direito civil e família advogado em Garanhuns",
    "direito das sucessões advogado em Garanhuns",
    "direito médico advogado em Garanhuns",
    "direito do consumidor advogado em Arcoverde",
    "direito do trabalho advogado em Arcoverde",
    "direito previdenciário advogado em Arcoverde",
    "direito civil e família advogado em Arcoverde",
    "direito das sucessões advogado em Arcoverde",
    "direito médico advogado em Arcoverde",
    "direito do consumidor advogado em Vitória de Santo Antão",
    "direito do trabalho advogado em Vitória de Santo Antão",
    "direito previdenciário advogado em Vitória de Santo Antão",
    "direito civil e família advogado em Vitória de Santo Antão",
    "direito das sucessões advogado em Vitória de Santo Antão",
    "direito médico advogado em Vitória de Santo Antão",
    "direito do consumidor advogado em Igarassu",
    "direito do trabalho advogado em Igarassu",
    "direito previdenciário advogado em Igarassu",
    "direito civil e família advogado em Igarassu",
    "direito das sucessões advogado em Igarassu",
    "direito médico advogado em Igarassu",
    "direito do consumidor advogado em Olinda",
    "direito do trabalho advogado em Olinda",
    "direito previdenciário advogado em Olinda",
    "direito civil e família advogado em Olinda",
    "direito das sucessões advogado em Olinda",
    "direito médico advogado em Olinda",
    "direito do consumidor advogado em Paulista",
    "direito do trabalho advogado em Paulista",
    "direito previdenciário advogado em Paulista",
    "direito civil e família advogado em Paulista",
    "direito das sucessões advogado em Paulista",
    "direito médico advogado em Paulista",
    "direito do consumidor advogado em Caruaru",
    "direito do trabalho advogado em Caruaru",
    "direito previdenciário advogado em Caruaru",
    "direito civil e família advogado em Caruaru",
    "direito das sucessões advogado em Caruaru",
    "direito médico advogado em Caruaru",
  ],
  openGraph: {
    title: "Paulo Moraes Advocacia e Consultoria Jurídica",
    description: "Escritório de advocacia em Recife especializado em direito do trabalho & previdenciário, Direito civil e família, consultoria jurídica personalizada. Atendimento profissional e confiança para proteger seus direitos.",
    url: "https://paulomoraesadv.com.br",  
    siteName: "Paulo Moraes Advocacia e Consultoria Jurídica",
    locale: "pt_BR",
    type: "website",
  },
  verification: {
    google: "C4f1ktvuCnAl_EhArfrA-NfT0XXr--6rpW0MyYY_2Cs",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="pt-BR" className={`${poppins.className} ${playfairDisplay.className} ${mulish.className}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
